# SPDX-FileCopyrightText: 2013-2020 Chimaine, MobTalkerScript contributors
#
# SPDX-License-Identifier: CC0-1.0

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: '^(.reuse/|LICENSES/)'
repos:
  - repo: https://git.fsfe.org/reuse/tool
    rev: v1.1.0
    hooks:
      - id: reuse
